---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
collections:
  _sections:
    default_front_matter_template: section
  _posts:
    default_front_matter_template: post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
