---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: image
  label: Image
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: updates
  label: Updates
  type: field_group_list
  fields:
  - type: datetime
    name: date
    label: Date
    config:
      date_format: DD/MM/YYYY
      required: true
  - name: title
    label: Title
    type: text
    hidden: false
    default: ''
  - type: textarea
    name: description
    label: Description
    config:
      wysiwyg: true
      schema:
        format: markdown
  hidden: false
  default: ''
- type: textarea
  name: footer
  label: Footer
  config:
    wysiwyg: true
    schema:
      format: markdown
